artifact_location: /home/chandi.s/ondemand/ClickTheLook/updated_runs/mlflow/445056506779992486
creation_time: 1775770871917
experiment_id: '445056506779992486'
last_update_time: 1775770871917
lifecycle_stage: active
name: updated_runs
trace_location: null
workspace: default
