artifact_uri: /home/chandi.s/ondemand/ClickTheLook/updated_runs/mlflow/445056506779992486/ab1537c0ba9a466b8d7bfbe34dd59064/artifacts
end_time: 1775801185278
entry_point_name: ''
experiment_id: '445056506779992486'
lifecycle_stage: active
run_id: ab1537c0ba9a466b8d7bfbe34dd59064
run_name: overjoyed-slug-911
source_name: ''
source_type: 4
source_version: ''
start_time: 1775801062080
status: 3
tags: []
user_id: chandi.s
