artifact_location: /home/chandi.s/ondemand/ClickTheLook/updated_runs/mlflow/558039572225846411
creation_time: 1775765977778
experiment_id: '558039572225846411'
last_update_time: 1775765977778
lifecycle_stage: active
name: ClickTheLook
trace_location: null
workspace: default
